### ISSUE TITLE
RadioRecord stream get Error

### ISSUE THREAD

**Issue by Angels-group** [vsmaks/audiostream-metadata-retriever#1]
```
E/AndroidRuntime: FATAL EXCEPTION: Thread-31969
                                                                    Process: by.angel.radiorecord, PID: 2650
                                                                    java.lang.NullPointerException
                                                                        at com.vodyasov.amr.AudiostreamMetadataRetriever.run(AudiostreamMetadataRetriever.java:87)
                                                                        at java.lang.Thread.run(Thread.java:841)
```

Try to get information from RadioRecord stream
**http://air2.radiorecord.ru:805/rr_320**

**Comment by allockye** [comment]
I solved it. check my pull request :)
